### ISSUE TITLE
Content is gone

### ISSUE THREAD

**Issue by timothyahaywood** [amyjko/bookish#335]
All text is now gone from each chapter. The images and chapter titles are still there, but the chapters are gone.

**Comment by amyjko** [comment]
Thanks for being the brave soul testing a buggy beta :) I'll investigate this weekend. (I do have backups and should be able to restore them, if they are indeed lost).

**Comment by timothyahaywood** [comment]
Not a big deal! I can always re-input the chapters if necessary. I know
you're extremely busy, but if you want to take a break and read the story
that would be fantastic. I'm open to anything—plot tweaks, character voice,
etc. I feel like the story is still in beta mode itself!

**Comment by amyjko** [comment]
Good news: I believe I found the defect causing the chapters to disappear; it shouldn't happen again. (There could always be other defects, however, so this is still very much in beta territory, and data loss is still possible).

Bad news: Although the text wasn't actually deleted, the way it was stored, there's no longer an association between the chapter text and the chapters, so I can't easily repair your particular book. It would be best to reenter the chapter text. Sorry about that!

I did add myself as an editor temporarily, just so I can see the book and edit it, so if you see my email address there, that's why.

**Comment by timothyahaywood** [comment]
So it looks like I can't get into the chapters or the browsing page copy
still. Only the cover page is accessible but none of the links work.

**Comment by amyjko** [comment]
Can you clarify what you mean by "the browsing page" copy? Do you mean while in reading mode or writing mode? (All of the links in the table of contents work for me while in writing mode).

**Comment by timothyahaywood** [comment]
It's the copy right above the table of contents, in writing mode.

**Comment by timothyahaywood** [comment]
Sure thing. Here's the URL: https://bookish.press/write/NCW758OSUmq6G7JllX1J
And a screen grab. The highlighted paragraph symbol is what I was talking
about.
[image: Screen Shot 2023-03-28 at 12.22.52 PM.png]

**Comment by amyjko** [comment]
Ah, image attachments don't via email replies unfortunately, so you'll have to paste or drag it on the GitHub website:

https://github.com/amyjko/bookish/issues/335

Thanks for the ink. While you're at it, it would be helpful to know what browser and operating system you're using.

**Comment by timothyahaywood** [comment]
Sorry about that!
