### ISSUE TITLE
Unclear how to create multi-line code snippets

### ISSUE THREAD

**Issue by rbohrer** [amyjko/bookish#343]
I have tried the following:

- Type multi-line text first, select it, click the code button (appears to have no effect)
- Type one line of code and hit newline inside of it (next line turns back to plain paragraph text)
- Highlight each line individually and hit the "code" button each time. Each line will highlight but there's no code-y background on the whitespace between the lines, so it does not feel like a single coherent code block. It would help my use case if the background color continued across lines in some kind of multiline code element

**Comment by amyjko** [comment]
There is multiline code block support, but it's actually a different type of content than inline code in a paragraph. You can find it next to the callout, quote, image, and table icons in the toolbar, with the `<>` icon.

<img width="203" alt="image" src="https://github.com/amyjko/bookish/assets/552276/89149732-741e-48ca-a56c-75ff30975f20">

This is a design and usability problem though: there's no interactive reason to distinguish between inline and block code. The reason it's currently this way is primarily because they have different formatting behavior: inline has no line breaks and is embedded in formatted text, whereas a multiline code block is a border and a caption. So it's primarily a typographic distinction.

A few ideas to improve the conceptual clarity of this:

* When someone does type a line break inside inline code, convert it to a block. That could be jarring, but at least it would signal that multiline code blocks are distinct typographically.
* Allow multiline inline code, which would enable arbitrary line breaks mid-paragraph. This would rarely be desired typographically, and would create a second type of multiline code behavior.

Other ideas, or preferences between the two above?

**Comment by rbohrer** [comment]
I like your first recommendation best. Although it could be jarring, it will make sure users know which options are available to them, and I think that outweighs the jarring aspect.

Excited to hear that multiline support is actually there :D time to go clean up some code snippets
