### ISSUE TITLE
Long copy-pasted URL runs off side of screen

### ISSUE THREAD

**Issue by rbohrer** [amyjko/bookish#347]
Low priority but I want to be thorough in reporting!

- Copy-paste the string "https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.cultstud.org%2Fwordpress%2Fvirtual-lecture-series%2F&data=05%7C01%7Crbohrer%40wpi.edu%7C4ac9148744674bd1809308db6757259a%7C589c76f5ca1541f9884b55ec15a0672a%7C0%7C0%7C638217396264752903%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=GatnLPMt8kAQWhLQ5H4LAMBeXO7NpTiqPXNxOl8tt9E%3D&reserved=0"
- Observe that it runs off the side of the page

**Comment by amyjko** [comment]
Clarification, since I can't reproduce this: where is this being pasted (chapter editor, or some other field?), and is it running off the side of the page in editing mode or reading mode? It'd also be helpful to know which browser you're using, in case there's a browser inconsistency about whitespace handling. Thanks!

**Comment by rbohrer** [comment]
I'm using Chrome Version 114.0.5735.134 (Official Build) (64-bit) on Windows 11 Home, on the editing interface. Here's a screenshot (the list should be irrelevant, was just there in my "scratch space" chapter already
![image](https://github.com/amyjko/bookish/assets/1960801/b85e1455-a105-4f0f-9698-d1741f3fdba7)
